"""MO2 instance reading, modlist round-trip, profile copies."""

from __future__ import annotations

import pytest

from aalo import mo2, runner

MODLIST = """\
# This file was automatically generated by Mod Organizer.
-Disabled Mod
+Enabled Mod
*Old Style Separator
+Alternative Addons & Patches_separator
+Another Enabled
"""


def test_modlist_roundtrip():
    ml = mo2.ModList.parse(MODLIST)
    assert ml.dumps() == MODLIST


def test_modlist_prefixes():
    ml = mo2.ModList.parse(MODLIST)
    assert ml.enabled_mods() == ["Enabled Mod", "Another Enabled"]
    assert ml.disabled_mods() == ["Disabled Mod"]
    seps = [e.name for e in ml.entries if e.is_separator]
    assert seps == ["Old Style Separator", "Alternative Addons & Patches_separator"]


def test_modlist_toggle_preserves_order():
    ml = mo2.ModList.parse(MODLIST)
    assert ml.set_enabled("Disabled Mod", True) is True
    assert ml.set_enabled("Nonexistent", True) is False
    out = ml.dumps().splitlines()
    assert out[1] == "+Disabled Mod"
    assert out[0].startswith("#")
    assert len(out) == len(MODLIST.splitlines())


def test_modlist_search_is_case_insensitive():
    ml = mo2.ModList.parse(MODLIST)
    assert [e.name for e in ml.search("enabled")] == ["Enabled Mod", "Another Enabled"]
    found = ml.find("enabled mod")
    assert found is not None and found.enabled is True


def test_modlist_save_and_reload(tmp_path):
    p = tmp_path / "modlist.txt"
    ml = mo2.ModList.parse(MODLIST, p)
    ml.set_enabled("Enabled Mod", False)
    ml.save()
    reloaded = mo2.ModList.load(p).find("Enabled Mod")
    assert reloaded is not None and reloaded.enabled is False


# -- real instance (read-only) ---------------------------------------------


def test_reads_the_real_instance(real_cfg, real_modlist):
    m = mo2.MO2(real_cfg)
    assert m.version.startswith("2.")
    assert m.selected_profile in m.profiles()
    assert m.game_path == real_cfg.anomaly


def test_real_modlist_roundtrip(real_cfg, real_modlist):
    m = mo2.MO2(real_cfg)
    raw = real_modlist.read_text(encoding="utf-8-sig")
    ml = m.modlist()
    assert ml.dumps().replace("\r\n", "\n") == raw.replace("\r\n", "\n")
    assert len(ml.mods()) > 100
    assert len(ml.enabled_mods()) > 0


def test_real_executables_include_the_launch_target(real_cfg):
    m = mo2.MO2(real_cfg)
    titles = [e.title for e in m.executables()]
    assert real_cfg.shortcut in titles
    exe = m.find_executable(real_cfg.shortcut)
    assert exe is not None
    assert exe.binary.lower().endswith(real_cfg.exe_name.lower())


def test_launch_commands(real_cfg):
    m = mo2.MO2(real_cfg)
    cmd = m.launch_command()
    assert cmd[0].endswith("ModOrganizer.exe")
    assert cmd[1] == f"moshortcut://:{real_cfg.shortcut}"

    # -p is a global MO2 option: it goes before "run", not after the program
    run_cmd = m.launch_command_run(profile="aalo-x")
    assert run_cmd[1:4] == ["-p", "aalo-x", "run"]
    assert run_cmd[-1].lower().endswith(real_cfg.exe_name.lower())

    # A non-default profile cannot be expressed as a shortcut, so command_for
    # must switch to the run form, running the configured executable by title.
    cmd = m.command_for(profile="aalo-x")
    assert cmd[1:4] == ["-p", "aalo-x", "run"]
    assert cmd[-2:] == ["-e", real_cfg.shortcut]
    assert m.command_for()[1].startswith("moshortcut://")


def test_game_args_force_the_run_form(real_cfg):
    m = mo2.MO2(real_cfg)
    args = runner.autoload_args("gammabaseline")
    cmd = m.command_for(game_args=args)
    # selected profile: no -p, but the args need "run -a"
    assert cmd[1:4] == ["run", "-a", args]
    assert cmd[-2:] == ["-e", real_cfg.shortcut]


def test_autoload_args():
    assert runner.autoload_args("gammabaseline") == "-start server(gammabaseline/single/alife/load) client(localhost)"
    assert runner.autoload_args("gammabaseline.scop") == runner.autoload_args("gammabaseline")
    for bad in ("", "a/b", "a(b)", 'a"b'):
        with pytest.raises(ValueError):
            runner.autoload_args(bad)


def test_copy_profile_creates_an_aalo_copy(real_cfg, real_modlist):
    m = mo2.MO2(real_cfg)
    name = None
    try:
        name = m.copy_profile("unittest")
        assert name == "aalo-unittest"
        copied = real_cfg.profiles_dir / name
        assert (copied / "modlist.txt").is_file()
        # Editing the copy leaves the source untouched.
        source_before = real_modlist.read_bytes()
        target = m.modlist(name).mods()[0].name
        assert m.set_mod_enabled(name, target, False) is True
        assert real_modlist.read_bytes() == source_before
        toggled = m.modlist(name).find(target)
        assert toggled is not None and toggled.enabled is False
    finally:
        if name:
            assert m.delete_profile(name) is True
            assert not (real_cfg.profiles_dir / name).exists()
